/**
 * scripts/generate-sitemap.mjs
 *
 * Regenerates public/sitemap.xml from scripts/seo-routes.mjs so the sitemap
 * can never drift from the routes the app actually exposes.
 *
 * Runs as a `prebuild`-style step in `npm run build` (before vite build),
 * so vite copies the freshly generated file from public/ into dist/ as part
 * of its normal asset pipeline. The file is also checked into git so the
 * intended sitemap state is always visible in PR diffs.
 *
 * Run standalone:  npm run sitemap
 */

import { readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { SITE_URL, SITEMAP_ROUTES } from "./seo-routes.mjs";

const __dirname = dirname(fileURLToPath(import.meta.url));
const OUT_PATH = resolve(__dirname, "..", "public", "sitemap.xml");

/** Format YYYY-MM-DD in UTC for stable cross-machine output. */
function todayIsoDate() {
  return new Date().toISOString().slice(0, 10);
}

function buildXml(routes) {
  const today = todayIsoDate();
  const urls = routes
    .map((route) => {
      const loc = route.path === "/" ? `${SITE_URL}/` : `${SITE_URL}${route.path}`;
      const lastmod = route.lastmod ?? today;
      const { priority, changefreq } = route.sitemap;
      return [
        "  <url>",
        `    <loc>${loc}</loc>`,
        `    <lastmod>${lastmod}</lastmod>`,
        `    <changefreq>${changefreq}</changefreq>`,
        `    <priority>${priority.toFixed(1)}</priority>`,
        "  </url>",
      ].join("\n");
    })
    .join("\n");

  return [
    '<?xml version="1.0" encoding="UTF-8"?>',
    '<!-- Auto-generated by scripts/generate-sitemap.mjs from scripts/seo-routes.mjs.',
    "     Do not edit by hand — your changes will be overwritten on the next build. -->",
    '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">',
    urls,
    "</urlset>",
    "",
  ].join("\n");
}

async function main() {
  const xml = buildXml(SITEMAP_ROUTES);

  // Skip the write (and avoid touching mtime / git) if nothing changed.
  let existing = "";
  try {
    existing = await readFile(OUT_PATH, "utf-8");
  } catch {
    // File doesn't exist yet — fall through and write.
  }
  if (existing === xml) {
    console.log(
      `[sitemap] up to date — ${SITEMAP_ROUTES.length} routes, no change to public/sitemap.xml`,
    );
    return;
  }

  await writeFile(OUT_PATH, xml, "utf-8");
  console.log(
    `[sitemap] wrote public/sitemap.xml — ${SITEMAP_ROUTES.length} routes`,
  );
}

main().catch((err) => {
  console.error("[sitemap] fatal:", err);
  process.exit(1);
});
